### PR TITLE
Implement arbitrary behind a feature flag

### LINKED ISSUE #34: Add implementation of arbitrary behind a feature flag
When replacing `String` with `SmolStr` it would also be useful for it to implement the `Arbitrary` trait from https://github.com/rust-fuzz/arbitrary.

This could be behind an `arbitrary` feature flag so it doesn't drag things in unnecessarily.

### PR DESCRIPTION
**Pull request by jeffa5**
Fixes #34

### CODE REVIEW

**Comment by matklad** [comment]
Could you bump the last component in Cargo.toml so that this is published automatically when merged?

**Comment by jeffa5** [comment]
Done :)

**Comment by matklad** [comment]
bors this+

**Comment by jeffa5** [comment]
Thanks @matklad!

**Pull request merged**
